Repository gonggibap/client, pull requests merged in 2024-10, with the labels that each got.

#8 feat : 오픈그래프 설정
  gonggibap/src/app/layout.tsx
Labels: docs 📄

#14 fix: #13 front -> client
  Jenkinsfile
Labels: bugfix 🐞

#19 deploy: #3 env 추가
  Jenkinsfile
  gonggibap/Dockerfile
Labels: setting File 📄

#21 fix : openGraph 이미지 수정, 설정 추가
  gonggibap/public/images/ogImage.png
  gonggibap/src/app/layout.tsx
Labels: docs 📄

#25 refactor : 프로바이더 분리
  gonggibap/src/app/layout.tsx
  gonggibap/src/app/page.tsx
  gonggibap/src/providers/RootProvider.tsx
  gonggibap/src/providers/ToastProvider.tsx
  gonggibap/src/providers/index.ts
Labels: refactoring ⚙️

#27 feat: #26 PM2 적용
  Jenkinsfile
  gonggibap/Dockerfile
Labels: feature 🛠

#30 feat : 소셜 로그인 기능
  gonggibap/public/images/logo.png
  gonggibap/src/app/auth/page.tsx
  gonggibap/src/app/layout.tsx
  gonggibap/src/app/login/page.tsx
  gonggibap/src/constants/routeURL.ts
  gonggibap/src/store/useAuthStore.ts
Labels: feature 🛠

#32 deploy: #31 젠킨스 파이프라인 최적화
  Jenkinsfile
Labels: refactoring ⚙️

#40 feat: #39 post 구문 추가
  Jenkinsfile
Labels: feature 🛠

#45 refactor : 에러 타입 수정
  gonggibap/src/apis/restaurant/useGetRestaurants.ts
  gonggibap/src/app/page.tsx
  gonggibap/src/types/apiResponse.ts
Labels: refactoring ⚙️

#46 refactor: api 호출 회수 감소
  gonggibap/src/app/page.tsx
  gonggibap/src/hooks/useCurrentLocation.ts
  gonggibap/src/hooks/useTouchHandler.ts
Labels: refactoring ⚙️

#48 bug : 빌드 에러 수정
  gonggibap/src/hooks/useCurrentLocation.ts
Labels: bugfix 🐞

#49 feat/#41/리뷰 기능 api 연결
  gonggibap/package-lock.json
  gonggibap/package.json
  gonggibap/src/apis/review/index.ts
  gonggibap/src/apis/review/useCreateReview.ts
  gonggibap/src/apis/review/useDeleteReview.ts
  gonggibap/src/apis/review/useGetReviews.ts
  gonggibap/src/apis/review/useUpdateReview.ts
  gonggibap/src/app/_components/RestaurantDetailView.tsx
  gonggibap/src/app/_components/ReviewForm.tsx
  gonggibap/src/app/_components/ThemeToggleBtn.tsx
  gonggibap/src/app/sample/page.tsx
  gonggibap/src/constants/queryKeys.ts
  gonggibap/src/types/review.ts
  gonggibap/src/types/sidebar.ts
Labels: feature 🛠

#51 refactor/#50/모바일 변경 로직 수정
  gonggibap/src/app/_components/DesktopSidebar.tsx
  gonggibap/src/app/_components/MobileSidebar.tsx
  gonggibap/src/app/_components/RestaurantDetailView.tsx
  gonggibap/src/app/_components/ReviewForm.tsx
  gonggibap/src/app/_components/Sidebar.tsx
Labels: refactoring ⚙️

#53 refactor/#52/시맨틱 태그 수정
  gonggibap/src/app/_components/DesktopSidebar.tsx
  gonggibap/src/app/_components/MobileSidebar.tsx
  gonggibap/src/app/_components/RestaurantDetailView.tsx
  gonggibap/src/app/_components/RestaurantListView.tsx
  gonggibap/src/app/_components/ReviewForm.tsx
  gonggibap/src/app/_components/Sidebar.tsx
Labels: refactoring ⚙️

#55 feat : 클러스터 추가, 마커 스타일 수정
  gonggibap/src/app/page.tsx
Labels: feature 🛠, refactoring ⚙️

#58 refactor : 마커 훅 분리
  gonggibap/src/app/page.tsx
  gonggibap/src/hooks/useMapMarkers.ts
Labels: refactoring ⚙️

#59 refactor : 지도 관련 로직 커스텀 훅 분리
  gonggibap/src/app/page.tsx
  gonggibap/src/hooks/useKakaoMap.ts
  gonggibap/src/hooks/useMapCluster.ts
  gonggibap/src/hooks/useMapMarkers.ts
  gonggibap/src/types/restaurant.ts
Labels: refactoring ⚙️

#60 refactor : 지도 상태 수정
  gonggibap/src/app/page.tsx
Labels: refactoring ⚙️

#61 design/#54/사이드바 UI 수정
  gonggibap/public/images/kakaomap.png
  gonggibap/src/apis/review/useCreateReview.ts
  gonggibap/src/app/_components/DesktopSidebar.tsx
  gonggibap/src/app/_components/RestaurantDetailView.tsx
  gonggibap/src/app/_components/RestaurantListView.tsx
  gonggibap/src/app/_components/ReviewForm.tsx
  gonggibap/src/app/page.tsx
  gonggibap/src/types/restaurant.ts
Labels: feature 🛠, design ✨

#62 design/#54/사이드바 UI 수정
  gonggibap/src/app/_components/RestaurantDetailView.tsx
  gonggibap/src/app/_components/RestaurantListView.tsx
  gonggibap/src/app/_components/ReviewForm.tsx
Labels: feature 🛠, design ✨

#69 feat : 카테고리 기능, ui
  gonggibap/package-lock.json
  gonggibap/package.json
  gonggibap/src/apis/restaurant/useGetRestaurants.ts
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/app/page.tsx
  gonggibap/src/constants/category.ts
  gonggibap/src/types/restaurant.ts
Labels: feature 🛠

#74 feat : 위치 리셋 버튼 이동
  gonggibap/src/app/_components/DesktopSidebar.tsx
  gonggibap/src/app/_components/MobileSidebar.tsx
  gonggibap/src/app/_components/Sidebar.tsx
  gonggibap/src/app/page.tsx
Labels: feature 🛠

#75 refactor/#71/컴포넌트 분리
  gonggibap/src/app/_components/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/Sidebar.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantAddress.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantCategory.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantItem.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantStats.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/index.ts
  gonggibap/src/app/_components/sidebar/restaurant/list/trackRestaurantSelection.ts
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/page.tsx
Labels: refactoring ⚙️

#77 refactor/#71/컴포넌트 분리
  gonggibap/next.config.mjs
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantHeader.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/index.ts
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewImages.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/index.ts
  gonggibap/src/app/page.tsx
Labels: feature 🛠

#80 feat/#78/공공기관 사용 내역 조회
  gonggibap/src/apis/history/useGetHistories.ts
  gonggibap/src/apis/restaurant/useGetRestaurants.ts
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/Sidebar.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/constants/queryKeys.ts
  gonggibap/src/types/history.ts
Labels: feature 🛠

#83 refactor : 카테고리 반응형 개수 조절
  gonggibap/src/app/_components/CategoryFilter.tsx
Labels: refactoring ⚙️
