Repository gonggibap/client, pull requests merged in 2024-11, with the labels that each got.

#87 design: 카테고리 디자인
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/constants/category.ts
  gonggibap/src/utils/getCategoryIcon.tsx
Labels: design ✨

#88 feat/#81/공공기관 사용 내역 조회 UI
  gonggibap/src/apis/history/useGetHistories.ts
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/TapNavigation.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/index.ts
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
  gonggibap/src/app/globals.css
  gonggibap/src/constants/queryKeys.ts
Labels: feature 🛠

#91 design : 맛집 디테일 디자인 수정
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantHeader.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/TapNavigation.tsx
Labels: design ✨

#92 feat/#89/식당 좋아요 api 연결
  gonggibap/src/apis/favorite/index.ts
  gonggibap/src/apis/favorite/useCreateFavoriteRestaurant.ts
  gonggibap/src/apis/favorite/useDeleteFavoriteRestaurant.ts
  gonggibap/src/apis/favorite/useGetFavoriteRestaurants.ts
  gonggibap/src/app/_components/ThemeToggleBtn.tsx
  gonggibap/src/app/_components/sidebar/favorite/FavoritesList.tsx
  gonggibap/src/app/_components/sidebar/favorite/index.ts
  gonggibap/src/app/_components/sidebar/restaurant/TapNavigation.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/TapNavigation.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/index.ts
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantAddress.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantCategory.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantItem.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantStats.tsx
  gonggibap/src/constants/queryKeys.ts
Labels: feature 🛠

#94 design : 맛집 디테일 디자인 수정
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantTapNavigation.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/index.ts
Labels: design ✨

#95 design : 상세페이지 디자인
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
  gonggibap/src/app/_components/sidebar/review/StarRating.tsx
  gonggibap/src/app/_components/sidebar/review/index.ts
  gonggibap/src/types/review.ts
  gonggibap/src/utils/getRelativeTime.ts
Labels: design ✨

#96 design : 맛집 디테일 디자인
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantTapNavigation.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
Labels: design ✨

#98 refactor : ReviewListItem 컴포넌트 분리
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewListItem.tsx
Labels: refactoring ⚙️

#101 feat : 식당 단건 조회
  gonggibap/src/apis/restaurant/useGetRestaurant.ts
  gonggibap/src/types/restaurant.ts
Labels: feature 🛠

#102 refactor : 맛집 상세정보 단일 조회 요청
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewListItem.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
Labels: refactoring ⚙️, design ✨

#106 feat : 식당 좋아요 조회, 추가, 삭제 기능
  gonggibap/src/apis/favorite/index.ts
  gonggibap/src/apis/favorite/useCreateFavoriteRestaurant.ts
  gonggibap/src/apis/favorite/useDeleteFavoriteRestaurant.ts
  gonggibap/src/apis/favorite/useGetFavoriteRestaurantCheck.ts
  gonggibap/src/apis/favorite/useGetFavoriteRestaurants.ts
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/constants/queryKeys.ts
Labels: feature 🛠

#107 refactor : 시맨틱태그 수정, 스크린 리더 지원
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantHeader.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantTapNavigation.tsx
Labels: refactoring ⚙️

#108 refactor : 현재 위치 마커 수정
  gonggibap/src/components/LoginConfirmationModal.tsx
  gonggibap/src/constants/marker.ts
  gonggibap/src/hooks/useKakaoMap.ts
Labels: refactoring ⚙️

#109 feat : 디테일뷰 로딩, 에러 처리
  gonggibap/src/apis/restaurant/useGetRestaurant.ts
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailErrorFallback.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailSkeleton.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantHeader.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/index.ts
  gonggibap/src/hooks/useKakaoMap.ts
Labels: feature 🛠

#110 feat : schema 마크업 추가
  gonggibap/src/app/layout.tsx
Labels: feature 🛠

#113 setting: 코드획일화
  gonggibap/.eslintrc.json
  gonggibap/package-lock.json
  gonggibap/package.json
  gonggibap/src/apis/core/client.ts
  gonggibap/src/apis/favorite/useCreateFavoriteRestaurant.ts
  gonggibap/src/apis/favorite/useDeleteFavoriteRestaurant.ts
  gonggibap/src/apis/favorite/useGetFavoriteRestaurantCheck.ts
  gonggibap/src/apis/favorite/useGetFavoriteRestaurants.ts
  gonggibap/src/apis/history/useGetHistories.ts
  gonggibap/src/apis/restaurant/useGetRestaurant.ts
  gonggibap/src/apis/restaurant/useGetRestaurants.ts
  gonggibap/src/apis/review/useCreateReview.ts
  gonggibap/src/apis/review/useDeleteReview.ts
  gonggibap/src/apis/review/useGetReviews.ts
  gonggibap/src/apis/user/getUserInfo.ts
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/app/_components/GoogleAnalytics.tsx
  gonggibap/src/app/_components/ThemeToggleBtn.tsx
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/Sidebar.tsx
  gonggibap/src/app/_components/sidebar/favorite/FavoritesList.tsx
  gonggibap/src/app/_components/sidebar/favorite/FavoritesListItem.tsx
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailErrorFallback.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantHeader.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantCategory.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantItem.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/trackRestaurantSelection.ts
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewListItem.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
  gonggibap/src/app/auth/_components/AuthContent.tsx
  gonggibap/src/app/auth/page.tsx
  gonggibap/src/app/entry/[id]/_components/DesktopSidebar.tsx
  gonggibap/src/app/entry/[id]/_components/MobileSidebar.tsx
  gonggibap/src/app/entry/[id]/_components/RestaurantDetailView.tsx
  gonggibap/src/app/entry/[id]/page.tsx
  gonggibap/src/app/layout.tsx
  gonggibap/src/app/login/page.tsx
  gonggibap/src/app/page.tsx
  gonggibap/src/components/LoginConfirmationModal.tsx
  gonggibap/src/hooks/useCurrentLocation.ts
  gonggibap/src/hooks/useKakaoMap.ts
  gonggibap/src/hooks/useMapMarkers.ts
  gonggibap/src/hooks/useRestaurantSearch.ts
  gonggibap/src/providers/RootProvider.tsx
  gonggibap/src/providers/ToastProvider.tsx
  gonggibap/src/store/useAuthStore.ts
  gonggibap/src/utils/getCategoryIcon.tsx
Labels: setting File 📄

#114 setting : 코드-획일화
  gonggibap/.eslintrc.json
  gonggibap/package-lock.json
  gonggibap/package.json
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/app/_components/MapCrosshair.tsx
  gonggibap/src/app/_components/MapPinLoading.tsx
  gonggibap/src/app/_components/Pagination.tsx
  gonggibap/src/app/_components/ThemeToggleBtn.tsx
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/favorite/FavoritesList.tsx
  gonggibap/src/app/_components/sidebar/favorite/FavoritesListItem.tsx
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailErrorFallback.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailSkeleton.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantHeader.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantTapNavigation.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantAddress.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantItem.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantStats.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/TapNavigation.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewImages.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewListItem.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
  gonggibap/src/app/auth/_components/AuthContent.tsx
  gonggibap/src/app/auth/_components/AuthSkeleton.tsx
  gonggibap/src/app/entry/[id]/_components/DesktopSidebar.tsx
  gonggibap/src/app/entry/[id]/_components/MobileSidebar.tsx
  gonggibap/src/app/entry/[id]/_components/RestaurantDetailView.tsx
  gonggibap/src/app/entry/[id]/_components/SearchBar.tsx
  gonggibap/src/app/entry/[id]/page.tsx
  gonggibap/src/app/login/page.tsx
  gonggibap/src/app/page.tsx
  gonggibap/src/components/LoginConfirmationModal.tsx
Labels: setting File 📄

#115 fix : 테일윈드 수정
  gonggibap/src/apis/favorite/useCreateFavoriteRestaurant.ts
  gonggibap/src/apis/favorite/useDeleteFavoriteRestaurant.ts
  gonggibap/src/apis/favorite/useGetFavoriteRestaurants.ts
  gonggibap/src/apis/history/useGetHistories.ts
  gonggibap/src/apis/restaurant/useGetRestaurant.ts
  gonggibap/src/apis/restaurant/useGetRestaurants.ts
  gonggibap/src/apis/review/useCreateReview.ts
  gonggibap/src/apis/review/useDeleteReview.ts
  gonggibap/src/apis/review/useGetReviews.ts
  gonggibap/src/apis/user/getUserInfo.ts
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
Labels: refactoring ⚙️

#116 setting : 코드 획일화
  gonggibap/.eslintrc.json
  gonggibap/src/apis/core/client.ts
  gonggibap/src/apis/favorite/useGetFavoriteRestaurantCheck.ts
  gonggibap/src/app/_components/GoogleAnalytics.tsx
  gonggibap/src/app/_components/ThemeToggleBtn.tsx
  gonggibap/src/app/_components/sidebar/Sidebar.tsx
  gonggibap/src/app/_components/sidebar/favorite/FavoritesList.tsx
  gonggibap/src/app/_components/sidebar/favorite/FavoritesListItem.tsx
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailErrorFallback.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantHeader.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantItem.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/trackRestaurantSelection.ts
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
  gonggibap/src/app/auth/_components/AuthContent.tsx
  gonggibap/src/app/entry/[id]/_components/DesktopSidebar.tsx
  gonggibap/src/app/entry/[id]/_components/MobileSidebar.tsx
  gonggibap/src/app/entry/[id]/_components/RestaurantDetailView.tsx
  gonggibap/src/app/entry/[id]/page.tsx
  gonggibap/src/app/layout.tsx
  gonggibap/src/app/page.tsx
  gonggibap/src/components/LoginConfirmationModal.tsx
  gonggibap/src/hooks/useKakaoMap.ts
  gonggibap/src/hooks/useMapMarkers.ts
  gonggibap/src/hooks/useRestaurantSearch.ts
  gonggibap/src/providers/RootProvider.tsx
  gonggibap/src/store/useAuthStore.ts
  gonggibap/src/utils/getCategoryIcon.tsx
Labels: setting File 📄

#120 feat : 모바일 검색기능
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/app/page.tsx
  gonggibap/src/components/SearchBar.tsx
Labels: feature 🛠

#121 refactor : 모바일 검색바 리팩토링
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/app/page.tsx
Labels: refactoring ⚙️

#122 fix : 검색 로직 수정
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/app/page.tsx
  gonggibap/src/components/SearchBar.tsx
Labels: refactoring ⚙️

#123 feat/#117/페이지네이션 UI
  gonggibap/src/app/_components/Pagination.tsx
  gonggibap/src/app/_components/sidebar/favorite/FavoritesList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/entry/[id]/_components/EntryPageContent.tsx
  gonggibap/src/app/entry/[id]/_components/FirstLoading.tsx
  gonggibap/src/app/entry/[id]/page.tsx
Labels: feature 🛠

#125 refactor: 식당-상세정보-리팩토링
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/page.tsx
Labels: refactoring ⚙️

#126 design : 로그인모달 레이아웃 수정
  gonggibap/src/components/LoginConfirmationModal.tsx
Labels: design ✨

#128 deploy: #127 도커 네트워크명 수정
  Jenkinsfile
Labels: deploy 🌐

#129 feat : 맛집 검색 empty 컴포넌트 생성
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantEmptyState.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
Labels: feature 🛠, refactoring ⚙️

#130 feat/#124/공유 페이지 검색 기능 구현
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/entry/[id]/_components/EntryPageContent.tsx
  gonggibap/src/app/page.tsx
Labels: feature 🛠

#132 feature/#131/공유페이지 검색시 메인 리다이렉트
  gonggibap/src/app/_components/FirstLoading.tsx
  gonggibap/src/app/_components/PageContent.tsx
  gonggibap/src/app/entry/[id]/_components/EntryPageContent.tsx
  gonggibap/src/app/entry/[id]/page.tsx
  gonggibap/src/app/page.tsx
Labels: feature 🛠

#134 fix : 카테고리 선택 로직 수정
  gonggibap/src/apis/restaurant/useGetRestaurants.ts
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/app/_components/PageContent.tsx
Labels: refactoring ⚙️

#135 fix : 좋아요 내역 쿼리 무효화
  gonggibap/src/apis/favorite/useGetFavoriteRestaurants.ts
Labels: bugfix 🐞

#136 refactor/#133/리뷰 리팩토링
  gonggibap/src/apis/review/useCreateReview.ts
  gonggibap/src/apis/review/useDeleteReview.ts
  gonggibap/src/apis/review/useGetReviews.ts
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/review/DeleteReviewDialog.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewListItem.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
  gonggibap/src/app/_components/sidebar/review/index.ts
  gonggibap/src/app/entry/[id]/_components/RestaurantDetailView.tsx
  gonggibap/src/types/userInfo.ts
Labels: refactoring ⚙️

#137 refactor : 카테고리 검색 수정
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/types/restaurant.ts
  gonggibap/src/utils/getCategoryIcon.tsx
Labels: refactoring ⚙️

#141 feat : 블로그 글 조회 api 생성
  gonggibap/src/apis/core/client.ts
  gonggibap/src/apis/restaurant/useGetBlogs.ts
  gonggibap/src/constants/queryKeys.ts
  gonggibap/src/types/restaurant.ts
Labels: feature 🛠

#142 fix : 코드 포멧팅
  gonggibap/src/apis/restaurant/index.ts
  gonggibap/src/apis/restaurant/useGetBlogs.ts
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
  gonggibap/src/app/_components/sidebar/review/index.ts
Labels: bugfix 🐞

#143 feat : 블로그 리뷰 추가
  gonggibap/src/app/_components/sidebar/restaurant/detail/BlogReview.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/index.ts
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewListItem.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
Labels: feature 🛠

#144 feat/#139/찜한 식당 조회 방법 수정
  gonggibap/src/apis/restaurant/useGetRestaurants.ts
  gonggibap/src/app/_components/CategoryFilter.tsx
  gonggibap/src/app/_components/PageContent.tsx
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/Sidebar.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/TapNavigation.tsx
  gonggibap/src/app/entry/[id]/_components/SearchBar.tsx
Labels: feature 🛠

#146 refactor/#145/찜한 목록 리패치
  gonggibap/src/apis/favorite/useCreateFavoriteRestaurant.ts
  gonggibap/src/apis/favorite/useDeleteFavoriteRestaurant.ts
  gonggibap/src/app/_components/PageContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
Labels: refactoring ⚙️

#148 feat/#147/공유 페이지 UI
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantHeader.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/entry/[id]/_components/DesktopSidebar.tsx
  gonggibap/src/app/entry/[id]/_components/MobileSidebar.tsx
  gonggibap/src/app/entry/[id]/_components/RestaurantDetailView.tsx
  gonggibap/src/app/login/page.tsx
  gonggibap/src/components/LoginConfirmationModal.tsx
Labels: feature 🛠

#150 design : 맛집 상세정보 디자인 수정
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
Labels: design ✨

#151 fix: 린트 에러 수정
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/login/page.tsx
Labels: bugfix 🐞

#152 design: 히스토리 디자인 수정
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
Labels: design ✨

#153 design : 디테일 뷰 식당 이름 픽셀 수정
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantHeader.tsx
Labels: design ✨

#155 refactor/#149/ux 개선
  gonggibap/src/apis/favorite/useDeleteFavoriteRestaurant.ts
  gonggibap/src/app/_components/Pagination.tsx
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
Labels: refactoring ⚙️

#156 feat : hotjar-설정
  gonggibap/next.config.mjs
Labels: feature 🛠

#157 feat: #154 hotjar 설정
  gonggibap/next.config.mjs
Labels: feature 🛠

#159 feat/#158/리뷰 업데이트
  gonggibap/next.config.mjs
  gonggibap/src/apis/review/useCreateReview.ts
  gonggibap/src/apis/review/useGetReviews.ts
  gonggibap/src/apis/review/useUpdateReview.ts
  gonggibap/src/app/_components/Pagination.tsx
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
  gonggibap/src/app/_components/sidebar/MobileSidebar.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewListItem.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
  gonggibap/src/types/review.ts
Labels: feature 🛠

#161 refactor/#160/리뷰 페이지네이션 수정
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
Labels: refactoring ⚙️

#162 refactor/#160/리뷰 페이지네이션 수정
  gonggibap/src/apis/history/useGetHistories.ts
  gonggibap/src/apis/review/useCreateReview.ts
  gonggibap/src/apis/review/useDeleteReview.ts
  gonggibap/src/apis/review/useGetReviews.ts
  gonggibap/src/apis/review/useUpdateReview.ts
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantDetailView.tsx
  gonggibap/src/app/_components/sidebar/restaurant/list/RestaurantListView.tsx
  gonggibap/src/app/_components/sidebar/review/DeleteReviewDialog.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewList.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewListItem.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewsContent.tsx
  gonggibap/src/constants/queryKeys.ts
  gonggibap/src/utils/getVisiblePageNumbers .ts
Labels: refactoring ⚙️

#164 design/#163/css 수정
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewForm.tsx
  gonggibap/src/app/_components/sidebar/review/ReviewListItem.tsx
Labels: design ✨

#167 refactor/#166/ui-ux-수정
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/BlogReview.tsx
Labels: refactoring ⚙️

#170 refactor/#169/유저-평점-평균-포매팅
  gonggibap/src/app/_components/sidebar/review/ReviewListItem.tsx
Labels: refactoring ⚙️

#172 refactor/#171/부가-기능-버튼-조정
  gonggibap/src/app/_components/ThemeToggleBtn.tsx
  gonggibap/src/app/_components/sidebar/DesktopSidebar.tsx
Labels: refactoring ⚙️

#174 feat: entry 메타데이터, openGraph 설정
  gonggibap/src/apis/restaurant/getServerRestaurant.ts
  gonggibap/src/app/_components/sidebar/history/HistoryContent.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/BlogReview.tsx
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/entry/[id]/layout.tsx
Labels: feature 🛠

#175 feat: 카카오톡 메시지 추가
  gonggibap/src/app/entry/[id]/layout.tsx
Labels: feature 🛠

#176 fix : openGraph 수정
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
  gonggibap/src/app/entry/[id]/layout.tsx
Labels: refactoring ⚙️

#177 refactor : 오픈그래프설정
  gonggibap/src/app/entry/[id]/layout.tsx
Labels: refactoring ⚙️

#180 refactor: 신고버튼 수정
  gonggibap/src/app/_components/sidebar/restaurant/detail/RestaurantInfo.tsx
Labels: refactoring ⚙️
